### ISSUE TITLE
Invalid path in README in environment setup

### ISSUE THREAD

**Issue by danielm1405** [mitsudome-r/pointcloud_delay_check#1]
@mitsudome-r 

Environment setup section point 4. says:
Add `export CYCLONEDDS_URI=file:///opt/autoware/cyclonedds_config.xml` at the bottom of `~/.bashrc` file

The file path is invalid in my case. I believe it should be changed to:
Add `export CYCLONEDDS_URI=file:///${HOME}/cyclonedds_configs/config.xml` (or wherever your DDS config from point 3. is located) at the bottom of `~/.bashrc` file

**Comment by mitsudome-r** [comment]
Thanks! This is now fixed.
